In [ ]:
# python library

 written c language
 functions from basic to advanced
 all numerical functiosn...Numerical python
 In 2005- Travis olliphant numpy as a library .
 use to facilitate complex mathematical and scientific operations by introducing array oriented computing capabilities


In [ ]:
#install numpy
pip install numpy

SyntaxError: invalid syntax (<ipython-input-1-5361eb23737e>, line 2)

In [ ]:
import numpy as np


In [ ]:
#create a numpy array
arr=np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [ ]:
arr=np.array(45)
arr

array(45)

In [ ]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1[0]

1

In [ ]:
arr1[2]

3

In [ ]:
arr2[0,1]

2

In [ ]:
arr2[1,2]

6

In [ ]:
arr2[1:2]

array([[4, 5, 6]])

In [ ]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sliced=arr3[:2,:2]

In [ ]:
sliced

array([[1, 2],
       [4, 5]])

In [ ]:
arr3[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#Basic operations you can perform on the arrays
a=np.array([[1,2],[4,5]])

b=np.array([4,5,6])
print("adding one to each element in array a:",a+1)
print("subtracting one from each elemnt in b:",b-1)


adding one to each element in array a: [[2 3]
 [5 6]]
subtracting one from each elemnt in b: [3 4 5]


In [ ]:
print("sum of all array elements:",a.sum())

sum of all array elements: 12


In [ ]:
# checking the datatype
a.dtype


dtype('int64')

In [ ]:
c=np .array([1.1,2.2,3.3])
c.dtype

dtype('float64')

In [ ]:
#Numpy copy and view
#copy__ create the copy of the array and owns the data where as view wontb owns the data and any change made to view will affect the original data also
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)


[1 2 3]


In [ ]:
print(b)

[100   2   3]


In [ ]:
a=np.array([1,2,3])
b=a.view()
b[0]=100
print(a)

[100   2   3]


In [ ]:
#shape of the array
a=np.array([[1,2,3],[4,5,6]])
a.shape


(2, 3)

In [ ]:
arr=np.array([1,2,3,4,5,6],ndmin=5)
arr


array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [ ]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
## iterating the array
a=np.array([[1,2,3],[4,5,6]])
for x in a:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
for x in a:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in a:
  for y in x:
    print(y)



1
2
3
4
5
6
7
8
9


array([100,   2,   3])

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,34]]])
for x in a:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
1
2
34


In [ ]:
# using nditer()
arr=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6


In [3]:
#join two numpy
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np

In [4]:
#join two dimensioanl arrays
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
arr=np.concatenate((arr1,arr2),axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
## stack
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.hstack((arr1,arr2))
arr


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [7]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.vstack((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
#### splitting the array
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [10]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [11]:
### searching the array
arr=np.array([1,2,3,4,5,6])
x=np.where(arr==4)
print(x)

(array([3]),)


In [12]:
arr=np.array([1,2,3,4,5,4,6,7,6])
x=np.where(arr==4)
print(x)

(array([3, 5]),)


In [13]:
## sorting
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [14]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [15]:
arr=np.array([True,False,True])
print(np.sort(arr))

[False  True  True]


In [16]:
#sorting 2d array
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [17]:
### filtering the array
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
newarr

array([41, 43])

In [18]:
# create a filter array that will return only values higher than 42
arr=np.array([41,42,43,44])
filter_arr=arr>42
filter_arr

array([False, False,  True,  True])

In [19]:
newarr=arr[filter_arr]
newarr

array([43, 44])

In [23]:
#how to generate the random numbers using random
from numpy import random
x=random.randint(100)
print(x)

73


In [26]:
y=random.rand()
y

0.6861619577419452

In [28]:
# create randomly 1d ARRAy
x=random.randint(100,size=(10))
x

array([62, 76, 35, 40,  1, 33, 52, 11, 79, 48])

In [29]:
#create randomly 2d array
x=random.randint(100,size=(5,3))
x

array([[55, 41, 41],
       [50, 22, 61],
       [53, 28, 56],
       [25,  0, 65],
       [75, 39, 77]])